const COA = [
  { kode: '11.01.00', nama: 'Kas', tipe: 'aset', saldo_normal: 'debit', kategori: 'Aset Lancar' },
  { kode: '11.03.00', nama: 'Deposito', tipe: 'aset', saldo_normal: 'debit', kategori: 'Aset Lancar' },
  { kode: '13.01.00', nama: 'Piutang Usaha', tipe: 'aset', saldo_normal: 'debit', kategori: 'Aset Lancar' },
  { kode: '13.01.11', nama: 'Piutang Rek Air - Tempat Ibadah (TI)', tipe: 'aset', saldo_normal: 'debit', kategori: 'Aset Lancar' },
  { kode: '13.01.14', nama: 'Piutang Rek Air - Panti Asuhan (PA)', tipe: 'aset', saldo_normal: 'debit', kategori: 'Aset Lancar' },
  { kode: '13.01.15', nama: 'Piutang Rek Air - Yayasan Sosial (YS)', tipe: 'aset', saldo_normal: 'debit', kategori: 'Aset Lancar' },
  { kode: '13.01.16', nama: 'Piutang Rek Air - Sekolah (S)', tipe: 'aset', saldo_normal: 'debit', kategori: 'Aset Lancar' },
  { kode: '13.01.21', nama: 'Piutang Rek Air - Rumah Tangga 1 (R1)', tipe: 'aset', saldo_normal: 'debit', kategori: 'Aset Lancar' },
  { kode: '13.01.22', nama: 'Piutang Rek Air - Rumah Tangga 2 (R2)', tipe: 'aset', saldo_normal: 'debit', kategori: 'Aset Lancar' },
  { kode: '13.01.23', nama: 'Piutang Rek Air - Rumah Tangga 3 (R3)', tipe: 'aset', saldo_normal: 'debit', kategori: 'Aset Lancar' },
  { kode: '13.01.31', nama: 'Piutang Rek Air - Niaga Kecil (NK)', tipe: 'aset', saldo_normal: 'debit', kategori: 'Aset Lancar' },
  { kode: '13.01.32', nama: 'Piutang Rek Air - Industri RT', tipe: 'aset', saldo_normal: 'debit', kategori: 'Aset Lancar' },
  { kode: '13.01.33', nama: 'Piutang Rek Air - Inst Pemerintah', tipe: 'aset', saldo_normal: 'debit', kategori: 'Aset Lancar' },
  { kode: '13.01.35', nama: 'Piutang Rek Air - Industri Besar (NB)', tipe: 'aset', saldo_normal: 'debit', kategori: 'Aset Lancar' },
  { kode: '13.01.36', nama: 'Piutang Rek Air - Pelabuhan', tipe: 'aset', saldo_normal: 'debit', kategori: 'Aset Lancar' },
  { kode: '13.01.40', nama: 'Piutang Adm & Dana Meter', tipe: 'aset', saldo_normal: 'debit', kategori: 'Aset Lancar' },
  { kode: '13.02.00', nama: 'Piutang Non Air', tipe: 'aset', saldo_normal: 'debit', kategori: 'Aset Lancar' },
  { kode: '13.03.00', nama: 'Piutang Mitra', tipe: 'aset', saldo_normal: 'debit', kategori: 'Aset Lancar' },
  { kode: '13.04.00', nama: 'Piutang Non Air (Bunga Deposito)', tipe: 'aset', saldo_normal: 'debit', kategori: 'Aset Lancar' },
  { kode: '14.01.00', nama: 'Penyisihan Piutang Usaha', tipe: 'aset', saldo_normal: 'kredit', kategori: 'Aset Lancar' },
  { kode: '15.01.00', nama: 'Persediaan Bahan Kimia', tipe: 'aset', saldo_normal: 'debit', kategori: 'Aset Lancar' },
  { kode: '15.02.00', nama: 'Persediaan BBM (Solar)', tipe: 'aset', saldo_normal: 'debit', kategori: 'Aset Lancar' },
  { kode: '15.03.00', nama: 'Persediaan Bahan Instalasi', tipe: 'aset', saldo_normal: 'debit', kategori: 'Aset Lancar' },
  { kode: '16.01.00', nama: 'Uang Muka Kerja', tipe: 'aset', saldo_normal: 'debit', kategori: 'Aset Lancar' },
  { kode: '31.01.00', nama: 'Aset Tetap', tipe: 'aset', saldo_normal: 'debit', kategori: 'Aset Tetap' },
  { kode: '32.01.00', nama: 'Akumulasi Penyusutan', tipe: 'aset', saldo_normal: 'kredit', kategori: 'Aset Tetap' },
  { kode: '33.01.00', nama: 'Aset Dalam Penyelesaian', tipe: 'aset', saldo_normal: 'debit', kategori: 'Aset Tetap' },
  { kode: '50.01.00', nama: 'Utang Usaha', tipe: 'kewajiban', saldo_normal: 'kredit', kategori: 'Kewajiban Lancar' },
  { kode: '50.01.01', nama: 'Utang Usaha - Bahan Kimia', tipe: 'kewajiban', saldo_normal: 'kredit', kategori: 'Kewajiban Lancar' },
  { kode: '71.01.00', nama: 'Kekayaan Pemda Yang Dipisahkan', tipe: 'ekuitas', saldo_normal: 'kredit', kategori: 'Ekuitas' },
  { kode: '76.01.00', nama: 'Laba Ditahan', tipe: 'ekuitas', saldo_normal: 'kredit', kategori: 'Ekuitas' },
  { kode: '77.01.00', nama: 'Laba Tahun Berjalan', tipe: 'ekuitas', saldo_normal: 'kredit', kategori: 'Ekuitas' },
  { kode: '81.01.10', nama: 'Pendapatan Harga Air', tipe: 'pendapatan', saldo_normal: 'kredit', kategori: 'Pendapatan' },
  { kode: '81.01.20', nama: 'Pendapatan Administrasi', tipe: 'pendapatan', saldo_normal: 'kredit', kategori: 'Pendapatan' },
  { kode: '81.01.30', nama: 'Pendapatan Air Mobil Tangki', tipe: 'pendapatan', saldo_normal: 'kredit', kategori: 'Pendapatan' },
  { kode: '81.02.10', nama: 'Pendapatan Sambungan Baru', tipe: 'pendapatan', saldo_normal: 'kredit', kategori: 'Pendapatan' },
  { kode: '81.02.20', nama: 'Pendapatan Penyambungan Kembali', tipe: 'pendapatan', saldo_normal: 'kredit', kategori: 'Pendapatan' },
  { kode: '81.02.50', nama: 'Pendapatan Denda', tipe: 'pendapatan', saldo_normal: 'kredit', kategori: 'Pendapatan' },
  { kode: '81.02.60', nama: 'Pendapatan Penggantian Meter Rusak', tipe: 'pendapatan', saldo_normal: 'kredit', kategori: 'Pendapatan' },
  { kode: '81.02.70', nama: 'Pendapatan Penggantian Pipa Persil', tipe: 'pendapatan', saldo_normal: 'kredit', kategori: 'Pendapatan' },
  { kode: '81.02.90', nama: 'Pendapatan Non Air Lainnya', tipe: 'pendapatan', saldo_normal: 'kredit', kategori: 'Pendapatan' },
  { kode: '91.01.00', nama: 'Beban Operasional Sumber Air', tipe: 'beban', saldo_normal: 'debit', kategori: 'Beban Operasi' },
  { kode: '92.02.00', nama: 'Beban Operasional Pengolahan', tipe: 'beban', saldo_normal: 'debit', kategori: 'Beban Operasi' },
  { kode: '92.02.90', nama: 'B. Pemeliharaan Pengolahan', tipe: 'beban', saldo_normal: 'debit', kategori: 'Beban Operasi' },
  { kode: '93.02.90', nama: 'B. Pemeliharaan Trandist Lainnya', tipe: 'beban', saldo_normal: 'debit', kategori: 'Beban Operasi' },
  { kode: '96.01.00', nama: 'Beban Pegawai', tipe: 'beban', saldo_normal: 'debit', kategori: 'Beban Umum & Adm' },
  { kode: '96.02.00', nama: 'Beban Kantor', tipe: 'beban', saldo_normal: 'debit', kategori: 'Beban Umum & Adm' },
  { kode: '96.02.90', nama: 'Rupa-Rupa Beban Kantor', tipe: 'beban', saldo_normal: 'debit', kategori: 'Beban Umum & Adm' },
  { kode: '96.03.00', nama: 'Beban Hubungan Langganan', tipe: 'beban', saldo_normal: 'debit', kategori: 'Beban Umum & Adm' },
  { kode: '96.04.00', nama: 'Beban Penelitian & Pengembangan', tipe: 'beban', saldo_normal: 'debit', kategori: 'Beban Umum & Adm' },
  { kode: '96.06.00', nama: 'Beban Pemeliharaan', tipe: 'beban', saldo_normal: 'debit', kategori: 'Beban Umum & Adm' },
  { kode: '96.06.20', nama: 'Pemeliharaan Kendaraan', tipe: 'beban', saldo_normal: 'debit', kategori: 'Beban Umum & Adm' },
  { kode: '96.06.50', nama: 'Beban Pemeliharaan Lainnya', tipe: 'beban', saldo_normal: 'debit', kategori: 'Beban Umum & Adm' },
  { kode: '96.07.00', nama: 'Biaya Umum Lainnya', tipe: 'beban', saldo_normal: 'debit', kategori: 'Beban Umum & Adm' },
  { kode: '96.08.00', nama: 'Rupa-Rupa Beban', tipe: 'beban', saldo_normal: 'debit', kategori: 'Beban Umum & Adm' },
  { kode: '96.08.80', nama: 'Beban Lain-lain', tipe: 'beban', saldo_normal: 'debit', kategori: 'Beban Umum & Adm' },
  { kode: '97.01.00', nama: 'Beban Pegawai Umum & Adm', tipe: 'beban', saldo_normal: 'debit', kategori: 'Beban Umum & Adm' },
  { kode: '97.06.20', nama: 'Pemeliharaan Kendaraan', tipe: 'beban', saldo_normal: 'debit', kategori: 'Beban Umum & Adm' },
  { kode: '98.08.80', nama: 'Beban Lain-lain', tipe: 'beban', saldo_normal: 'debit', kategori: 'Beban Umum & Adm' },
];

module.exports = COA;
